global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#egfwd-aws-devops'
    send_resolved: true
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    text: "- *Alert*: {{ .CommonAnnotations.summary }}\n- *Description*: {{ .CommonAnnotations.description }}"