global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - localhost:9093
scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIARZTDE7EUA2T6FW5U
        secret_key: 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
        port: 9100